# Generated by Django 3.0.8 on 2020-08-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_site',
            new_name='Anysitelink',
        ),
    ]
