# Generated by Django 3.0.8 on 2020-08-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_auto_20200818_2150'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofileinfo',
            table='user_info',
        ),
    ]
