# Generated by Django 3.0.8 on 2020-08-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_auto_20200818_2222'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofileinfo',
            table=None,
        ),
    ]
